name: Android CI

on:
  push:
    branches:
      - main  # 触发编译的分支，可以根据需要调整
  pull_request:
  workflow_dispatch:  # 添加手动触发的事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17  # 设置所需的 JDK 版本，Android Gradle Plugin 现在要求 JDK 11+
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33 # 需要与您的项目匹配的 API 级别
        build-tools: 33.0.2 # 需要与项目兼容的 Build Tools 版本

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease # 编译 release 版本 APK

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
